### ISSUE TITLE
Missing file 

### ISSUE THREAD

**Issue by shoroqtrad** [AngelFelipeMP/Transformers-for-Arabic-hate-speech-and-offensive-language#1]
Hello, 
I couldn't find config.py file,

**Comment by AngelFelipeMP** [comment]
Hi shoroqtrad,

Drop me an email, and I will provide you with the file.
Regards,

**Comment by shoroqtrad** [comment]
Hi angle ,
Iam shrouq trad from github
I want config.py
Thank you

**Comment by shoroqtrad** [comment]
thank you so much
